#!/usr/bin/env python3
"""将 markdown 报告转换为手机微信友好的 HTML 格式"""
import sys, os, glob
from pathlib import Path

CSS = """
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;font-size:16px;line-height:1.75;color:#222;background:#f5f5f5;padding:10px;max-width:720px;margin:0 auto}
.card{background:#fff;border-radius:10px;padding:18px 14px;margin-bottom:12px;box-shadow:0 1px 3px rgba(0,0,0,0.06)}
h1{font-size:20px;color:#c62828;text-align:center;margin-bottom:8px}
h2{font-size:17px;color:#c62828;margin:14px 0 8px;padding-bottom:6px;border-bottom:2px solid #ffcdd2}
h3{font-size:15px;color:#333;margin:10px 0 6px}
h4{font-size:14px;color:#555;margin:8px 0 4px}
p{margin:6px 0;font-size:14px}
ul,ol{padding-left:18px;font-size:14px}
li{margin:3px 0}
strong{color:#333}
a{color:#1565c0;text-decoration:none}
table{width:100%;border-collapse:collapse;font-size:13px;margin:8px 0}
th,td{padding:6px 4px;text-align:left;border-bottom:1px solid #eee}
th{background:#fafafa;color:#555;font-weight:600}
tr:last-child td{border-bottom:none}
pre{background:#f5f5f5;border-left:3px solid #ccc;padding:8px 10px;font-size:12px;margin:6px 0;border-radius:4px;overflow-x:auto;white-space:pre-wrap}
code{background:#f0f0f0;padding:1px 4px;border-radius:3px;font-size:13px}
blockquote{border-left:3px solid #ffcdd2;padding:6px 10px;margin:8px 0;color:#666;background:#fff5f5;border-radius:4px;font-size:13px}
hr{border:none;border-top:1px dashed #ddd;margin:14px 0}
.meta{text-align:center;color:#999;font-size:12px;margin-bottom:10px}
@media(max-width:400px){body{padding:6px;font-size:15px}.card{padding:12px 8px}table{font-size:12px}}
"""

def convert(md_path):
    import markdown2
    with open(md_path,"r",encoding="utf-8") as f:
        md = f.read()
    body = markdown2.markdown(md, extras=["tables","fenced-code-blocks","break-on-newline","header-ids"])
    title = Path(md_path).stem.replace("_"," ")
    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>{title}</title>
<style>{CSS}</style>
</head>
<body>
<div class="card">
{body}
</div>
<p class="meta">Generated by daily_stock_analysis · 算价公司投资部</p>
</body>
</html>"""

def main():
    d = sys.argv[1] if len(sys.argv) > 1 else "reports"
    if not os.path.isdir(d):
        print(f"SKIP: {d} not found"); return
    mds = glob.glob(os.path.join(d,"*.md"))
    for f in mds:
        html = convert(f)
        out = f.replace(".md",".html")
        with open(out,"w",encoding="utf-8") as fh:
            fh.write(html)
        print(f"OK {os.path.basename(f)} -> {os.path.basename(out)} ({len(html)} chars)")

if __name__=="__main__":
    main()
